default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: topproducts_development

test:
  <<: *default
  database: topproducts_test

production:
  <<: *default
  database: topproducts_production
  username: topproducts
  password: <%= ENV['TOPPRODUCTS_DATABASE_PASSWORD'] %>
